import Head from "next/head";
import styles from "../styles/Home.module.css";
import Charts from "./charts";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to learning algorithms wity react.js
        </h1>

        <p className={styles.description}>please select an algorithm.</p>
        <Charts />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Mustafa-Zahedi"
          target="_blank"
          rel="noopener noreferrer"
        >
          made by <span className="text-xl font-medium mx-2">Zahedi</span>
        </a>
      </footer>
    </div>
  );
}
