import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to learning sorting algorithms</h1>
        <div className="my-5"></div>
        <Link href={"/insertion"}>Insertion Sort</Link>
      </main>
    </div>
  );
}
